### PR TITLE
Added swagger.io documentation to api endpoints

### PR DESCRIPTION
**Pull request by AdamZarger**
Converted the API documentation for the CCDB 5 from [the gist](https://github.com/cfpb/ccdb5-api/wiki/API-Specification) to Swagger.io for the `search`, `suggest`, and `document` endpoints. Also added a new endpoint `/docs/` to view the documentation via the Swagger UI.

Reviewers:
@amymok 
@JeffreyMFarley 
@sephcoster 

To Do:
* The version of Swagger we must use requires named API endpoints in order for the UI to function. Currently, `search` and `document` are unnamed endpoints (requiring arguments instead), and are not picked up by Swagger UI.

**Screenshot of Swagger UI, collapsed**
swagger ui - no name endpoints collapsed

**Screenshot of Swagger UI, expanded**
swagger ui - no name endpoints expanded

**Screenshot of Swagger UI after naming the endpoints, partially expanded**
swagger ui - named endpoints

### CODE REVIEW

**Comment by JeffreyMFarley** [comment]
>The version of Swagger we must use requires named API endpoints in order for the UI to function. Currently, search and document are unnamed endpoints (requiring arguments instead), and are not picked up by Swagger UI.

The API is implemented correctly, I would submit that the docs should change to match how the API functions

**Comment by AdamZarger** [comment]
@JeffreyMFarley 
Sorry, I don't think I explained the screenshots in my comment well enough:

The code changes that make up this PR are based on the API spec and are detailed by the **Screenshot of Swagger UI, collapsed** and **Screenshot of Swagger UI, expanded** screenshots. That's what the Swagger UI looks like with `/` (search) and `/{id}/` (document) endpoints.

The third screenshot, **Screenshot of Swagger UI after naming the endpoints, partially expanded**, shows a change I made (`/{id}/` => `/_document/{id}/`) but did not push. I only made that change to demonstrate the limitations of the Swagger version we're using.

The actual Swagger docs are detailed in `views.py`, and did not have any changes made to them between the set of screenshots. The issue I am having is figuring out how to force Swagger to recognize that `/` and `/{id}/` are named endpoints with docs to display without having to modify/name the endpoints themselves.

Does that explanation make sense?

**Comment by AdamZarger** [comment]
@JeffreyMFarley @amymok @sephcoster 

I've been working on this locally in between all the CRDB stuff. I've confirmed that the form the code is in is basically the best we can get it at the moment. All the documentation is there on the views, but due to the dependency issues between Swagger UI version and Django Rest Framework version, the Swagger UI does not work for the search or document endpoints. The Swagger UI will work for the _suggest endpoint as it is. Thoughts?

**Comment by JeffreyMFarley** [comment]
Can you describe these dependency issues?  Also, I'm not sure why Swagger would have an issue with root endpoints (to me `/` is a root endpoint and not "unnamed")

**Comment by AdamZarger** [comment]
Sure! I initially tried to use [Django REST Swagger](https://django-rest-swagger.readthedocs.io/en/latest/), which we cannot use because it requires a Django Rest Framework version of 3.5. I tried to work around this by using Swagger UI version 2.0 and pointing it at a single JSON file with the entire documentation in it, but despite that it still threw errors expecting DRF 3.5.

Instead I tried to imitate the Swagger UI 0.3.0 documentation endpoint that we have for MED Search, which involves annotating each view as shown in this PR. This works for the most part, except for the problem with the root endpoint. I've done a significant amount of research trying to get around that "nameless" endpoint issue, but I think it's a limitation of the particular version of Swagger UI.

I'm open to suggestions for other documentation approaches if there are any ideas. I also looked into [Django REST Framework's built-in docs](http://www.django-rest-framework.org/topics/documenting-your-api/) options, but they don't seem to be as detailed as we'd like.

**Comment by AdamZarger** [comment]
@sephcoster @amymok @JeffreyMFarley 

While working on something else, I realized that the documentation I added to each view DOES show up when pinging the view with Django Rest Framework. Though the Search and Document endpoint documentation doesn't appear in the Swagger UI, the documentation is available via the API and DRF. Do we think that's enough to close this story?

**Comment by JeffreyMFarley** [comment]
Thanks for your hard work @AdamZarger!

But I am going to deprecate this PR and open another

**Pull request closed without merging**
